----------------------------------------------------------------------------------
-- Company: SEONGSAN Lab
-- This file was generated by scode
-- DONOT EDIT MANUALLY !!!
----------------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.scode_util.all;

entity test is
    port (
        clk                 : in std_logic;
        reset               : in std_logic
    );
end entity;

architecture arch_test of test is

begin

    process(clk)
    begin
        if rising_edge(clk) then 
            if reset = '1' then
            end if;
        end if;
    end process;

end architecture;
